# Generated by Django 3.2.5 on 2021-09-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Pr', 'Peshawar'), ('Lr', 'Lahore'), ('Isl', 'Islamabad')], default='Pr', max_length=3)),
                ('typ', models.CharField(choices=[('Inv', 'Invoice'), ('Quo', 'Quotation'), ('Rep', 'Report')], default='Inv', max_length=3)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=50)),
                ('ProjectID', models.CharField(max_length=12)),
                ('Location', models.CharField(max_length=100)),
                ('ProjectName', models.CharField(max_length=50)),
                ('NoOfBH', models.CharField(max_length=10)),
                ('DepthOfBH', models.CharField(max_length=20)),
                ('Drilling_Method', models.CharField(max_length=50)),
                ('DateOfDrilling', models.DateTimeField(auto_now=True)),
                ('ReportingOfficer', models.CharField(max_length=50)),
                ('SubmittedTo', models.CharField(max_length=50)),
                ('GroundWaterTableDepth', models.CharField(max_length=50)),
                ('InvoiceTypes', models.CharField(choices=[('F&D', 'Feasibility & Designs'), ('Cons', 'Consultancy'), ('Op', 'Operation')], default='Cons', max_length=5)),
                ('InvAmount', models.CharField(max_length=50)),
                ('QuotAmount', models.CharField(max_length=50)),
                ('QuotClientName', models.CharField(max_length=50)),
            ],
        ),
    ]
