# Generated by Django 3.2.5 on 2021-09-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0002_auto_20210903_0726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceProgressModel',
        ),
        migrations.DeleteModel(
            name='QuotationProgressModel',
        ),
        migrations.DeleteModel(
            name='ReportProgressModel',
        ),
        migrations.RemoveField(
            model_name='progressmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='progressmodel',
            name='typ',
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='DateOfDrilling',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='DepthOfBH',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='Drilling_Method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='GroundWaterTableDepth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='InvAmount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='InvoiceTypes',
            field=models.CharField(blank=True, choices=[('F&D', 'Feasibility & Designs'), ('Cons', 'Consultancy'), ('Op', 'Operation')], default='Cons', max_length=5),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='NoOfBH',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='ProjectID',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='QuotAmount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='QuotClientName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='ReportingOfficer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='SubmittedTo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='progressmodel',
            name='added_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
