# Generated by Django 3.2.5 on 2021-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0003_auto_20210907_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressmodel',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='progressmodel',
            name='added_by',
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='city',
            field=models.CharField(choices=[('Pr', 'Peshawar'), ('Lr', 'Lahore'), ('Isl', 'Islamabad')], default='Pr', max_length=3),
        ),
        migrations.AddField(
            model_name='progressmodel',
            name='typ',
            field=models.CharField(choices=[('Inv', 'Invoice'), ('Quo', 'Quotation'), ('Rep', 'Report')], default='Inv', max_length=3),
        ),
    ]
