# Generated by Django 3.2.5 on 2021-09-09 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0004_auto_20210909_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressmodel',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
